version = 0.1
[default]
[default.pipeline_bootstrap]
[default.pipeline_bootstrap.parameters]
pipeline_user = "arn:aws:iam::723526694744:user/aws-sam-cli-managed-dev-pipeline-reso-PipelineUser-ZA4HU308N66Q"
permissions_provider = "AWS IAM"

[dev]
[dev.pipeline_bootstrap]
[dev.pipeline_bootstrap.parameters]
pipeline_execution_role = "arn:aws:iam::723526694744:role/aws-sam-cli-managed-dev-pipe-PipelineExecutionRole-1U7IYBCS3SZXL"
cloudformation_execution_role = "arn:aws:iam::723526694744:role/aws-sam-cli-managed-dev-p-CloudFormationExecutionR-1BCMDY52JHWPK"
artifacts_bucket = "aws-sam-cli-managed-dev-pipeline-artifactsbucket-fygwxzy1jz2u"
image_repository = ""
region = "ap-southeast-2"

[prod]
[prod.pipeline_bootstrap]
[prod.pipeline_bootstrap.parameters]
pipeline_execution_role = "arn:aws:iam::723526694744:role/aws-sam-cli-managed-prod-pip-PipelineExecutionRole-1BOVTYEP0NNHY"
cloudformation_execution_role = "arn:aws:iam::723526694744:role/aws-sam-cli-managed-prod-CloudFormationExecutionR-EEHJL82N3ORQ"
artifacts_bucket = "aws-sam-cli-managed-prod-pipeline-artifactsbucket-1ifbish4xjqrw"
image_repository = ""
region = "ap-southeast-2"
